# Generated by Django 3.0.3 on 2020-02-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pven', models.CharField(max_length=100, verbose_name='prod_ven')),
                ('prew', models.CharField(max_length=100, verbose_name='prod_rew')),
                ('active', models.CharField(default='Y', max_length=10, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, verbose_name='prod_name')),
                ('pprice', models.FloatField(verbose_name='prod_price')),
                ('pqty', models.IntegerField(verbose_name='prod_qty')),
                ('pcat', models.CharField(max_length=50, verbose_name='prod_cat')),
                ('active', models.CharField(default='Y', max_length=10, verbose_name='active')),
                ('vendorref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app1.Vendor')),
            ],
        ),
    ]
